---
title: Nodes
toc: true
toc-depth: 3
fig-align: center
---

The nodes that are included with Molecular Nodes, are all pre-built and included with the add-on.
They work the same as any of the other nodes inside of Geometry Nodes, and can, if used, also process the data from 3D models like a cube or a monkey.
They are designed with molecular data & use cases in mind, but they are not limited to usage with molecular data.

All of the nodes that are included are documented here, with descriptions, extra info about inputs and outputs, sometimes small demo videos showing the intended use cases of the nodes.

Experimentation is highly encouraged, combining these nodes with others to see what kind of results you can get.
Molecular Nodes came about through experimentation with nodes, and there is no better way to learn the systems then to keep plugging and unplugging different sockets, changing values and tinkering.

At any point you can view the internals of the node groups that are included with Molecular Nodes.
With a node selected, you can <kbd>Tab</kbd> to enter a selected node, and use <kbd>Ctrl</kbd> + <kbd>Tab</kbd> to exit the node group.
You can also do the same by right clicking.
Feel free to tweak the internals of node groups, but beware that changing one node group will change that node group for all othe uses of it.
Starting a new Blender session will ensure that the node groups are fresh and 'factor reset'.

