# Auto-generated by nodebpy.assets.generate_asset_api — do not edit manually.
from typing import TYPE_CHECKING
from nodebpy.builder import (
    AssetShaderGroup,
    ColorSocket,
    FloatSocket,
    PackageLibrary,
    SocketAccessor,
)


class MNColor(AssetShaderGroup):
    """MN Color"""

    _name = "MN Color"
    _asset_name = "MN Color"
    _library = PackageLibrary(__file__, "../assets/node_data_file.blend")

    class _Inputs(SocketAccessor):
        pass

    class _Outputs(SocketAccessor):
        color: ColorSocket
        """Color"""
        alpha: FloatSocket
        """Alpha"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(self):
        super().__init__(**{})


__all__ = ("MNColor",)
