# Auto-generated by nodebpy.assets.generate_asset_api — do not edit manually.
from typing import TYPE_CHECKING, Literal
from nodebpy.builder import (
    AssetShaderGroup,
    ColorSocket,
    FloatSocket,
    MenuSocket,
    PackageLibrary,
    ShaderSocket,
    SocketAccessor,
)
from nodebpy.types import (
    InputColor,
    InputFloat,
    InputMenu,
)


class ColorAO(AssetShaderGroup):
    """Color AO"""

    _name = "Color AO"
    _asset_name = "Color AO"
    _library = PackageLibrary(__file__, "../assets/node_data_file.blend")

    class _Inputs(SocketAccessor):
        color: ColorSocket
        """Color"""
        menu: MenuSocket
        """Menu"""
        distance: FloatSocket
        """Distance"""
        exponent: FloatSocket
        """Exponent"""

    class _Outputs(SocketAccessor):
        result: ColorSocket
        """Result"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        color: InputColor = None,
        menu: InputMenu | Literal["AO", "None"] = "AO",
        distance: InputFloat = 1.0,
        exponent: InputFloat = 2.0,
    ):
        super().__init__(
            **{
                "Socket_0": color,
                "Socket_1": menu,
                "Socket_2": distance,
                "Socket_4": exponent,
            }
        )


class Flat(AssetShaderGroup):
    """Flat"""

    _name = "Flat"
    _asset_name = "Flat"
    _library = PackageLibrary(__file__, "../assets/node_data_file.blend")

    class _Inputs(SocketAccessor):
        outline: MenuSocket
        """Outline"""
        threshold: FloatSocket
        """Threshold"""
        thickness: FloatSocket
        """Thickness"""

    class _Outputs(SocketAccessor):
        emission: ShaderSocket
        """Emission"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        outline: InputMenu | Literal["Outline", "None"] = "Outline",
        threshold: InputFloat = 0.8,
        thickness: InputFloat = 0.15,
    ):
        super().__init__(
            **{"Socket_3": outline, "Socket_1": threshold, "Socket_2": thickness}
        )


class MNColor(AssetShaderGroup):
    """MN Color"""

    _name = "MN Color"
    _asset_name = "MN Color"
    _library = PackageLibrary(__file__, "../assets/node_data_file.blend")

    class _Inputs(SocketAccessor):
        pass

    class _Outputs(SocketAccessor):
        color: ColorSocket
        """Color"""
        alpha: FloatSocket
        """Alpha"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(self):
        super().__init__(**{})


class OutlineMask(AssetShaderGroup):
    """Outline Mask"""

    _name = "Outline Mask"
    _asset_name = "Outline Mask"
    _library = PackageLibrary(__file__, "../assets/node_data_file.blend")

    class _Inputs(SocketAccessor):
        threshold: FloatSocket
        """Threshold"""
        thickness: FloatSocket
        """Thickness"""

    class _Outputs(SocketAccessor):
        outline: FloatSocket
        """Outline"""

    if TYPE_CHECKING:

        @property
        def i(self) -> _Inputs: ...
        @property
        def o(self) -> _Outputs: ...

    def __init__(
        self,
        threshold: InputFloat = 0.8,
        thickness: InputFloat = 0.15,
    ):
        super().__init__(**{"Socket_2": threshold, "Socket_1": thickness})


__all__ = (
    "ColorAO",
    "Flat",
    "MNColor",
    "OutlineMask",
)
