---
title: Node Trees
subtitle: Using `nodebpy` to create and edit node trees
---

Molecular Nodes uses `nodebpy` for creating and changing the node trees - Geometry, Shader and Compositor.

This allows for replicating the node-based workflows from the GUI, enabling the full power of Geometry Nodes (GN) and the other node editors from within a script.

The approach of `nodebpy` is to overload the `>>` operator, which instead acts as a "node link" operator when used inside of a node tree. We can access and edit the GN node tree using the `mol.tree` property. This is a `nodebpy.TreeBuilder` subclass for editing the tree.


```{python}
import math
import molecularnodes as mn
import molecularnodes.nodes.geometry as mg
from nodebpy import geometry as g

cv = mn.Canvas(mn.scene.Cycles(32))
```

Editing of a node tree looks like below, where entering the context manager resets the node tree with an `Atoms` input and a `Join Geometry` already set up. Each object that is created with the class adds a node, and the nodes are linked either by neing passed as arguments to the class constructors or linking with the `>>` operator. The code and the resulting node tree that is produced is shown below.
```{python}
mol = mn.Molecule.fetch("1bna")
mat = mn.material.Default().material

with mol.tree.reset() as (atoms, join):
    (
        atoms
        >> mg.SeparateAtoms(selection=mg.IsSolvent().o.inverted)
        >> mg.StyleSpheres(material=mat)
        >> join
    )

mol.tree
```

We now use the `Canvas` to make the camera look at our `Molecule` and render a snapshot.

```{python}
cv.look_at(mol)
cv.snapshot()
```


## Non-Linear Node Trees

The of Geometry Nodes comes from the non-linear nature of working with node trees. We can express complex systems with relatively simple node setups.

```{python}
with mol.tree.reset() as (atoms, join):
    atoms = (
        atoms
        >> mg.SeparateAtoms(selection=~mg.IsSolvent())
        >> mg.CentreOnSelection()
        >> mg.GeoemtryToPlanar() 
        >> g.TransformGeometry(rotation=(0, math.pi/2, 0))
    )

    for x in [-1, 0, 1]:
        (
            atoms
            >> g.TransformGeometry(
                translation=(x * 3, 0, 0),
                rotation=(0, 0, x * (math.pi / 4))
            )
            >> mg.StyleSpheres(material=mat)
            >> join
        )

mol.tree
```

```{python}
cv.look_at(mol)
cv.snapshot()
```

We can use this non-linear approach to create two different styles and apply them to the same molecule.
Each branch applys a new color scheme with the `SetColor` node and then applies one of the two styles.
Both style branches are joined back together with the `Join Geometry` node that is added by default
after calling the `mol.tree.reset()` to create the tree context.

```{python}
cv.clear()
cv.engine = mn.scene.EEVEE()
mol = mn.Molecule.fetch("8H1B")

mat = mn.material.Flat(threshold=0.2).material
# mat = mn.material.Default().material

with mol.tree.reset() as (atoms, join):
    # creating one branch / chain of nodes for Ball and Stick style
    (
        atoms
        >> mg.SetColor(
            color=mg.ColorCommon(carbon=mg.RandomColor(id=mg.ChainID()))
        )
        >> mg.StyleSticks(
            selection=mg.IsSideChain() & mg.IsPeptide(),
            scale=0.6,
            material=mat
        )
        >> mg.StyleSurface(selection=mg.IsNucleic(), material=mat)
        >> join
    )

    # creating a second branch, where we apply a different color and style
    # but join it back into the same `Join Geometry` node
    (
        atoms
        >> mg.SetColor(color=mg.ColorRainbow())
        >> mg.StyleCartoon(
            selection=mg.IsPeptide(),
            quality=5,
            loop_radius=0.6,
            material=mat
        )
        >> join
    )

mol.tree
```



```{python}
cv.look_at(mol)
cv.snapshot()
```


```{python}
cv.resolution = (1080, 1080)
cv.look_at(mol)

with mol.tree.reset() as (atoms, join):
    # we select atoms that are within 4.0 angstrom of the nucleic atoms; the expand=True
    # means 
    sel_prox = (
        mg.SelectProximity(atoms,subset=mg.IsNucleic(),expand=True, distance_a=4.0) 
        & mg.IsPeptide() 
        & mg.IsSideChain()
    )

    atoms = atoms >> mg.SetColor(color=mg.ColorRainbow())
    (
        atoms
        >> mg.StyleCartoon(selection=mg.IsPeptide(),loop_radius=0.6, material=mat)
        >> mg.StyleSurface(selection=mg.IsNucleic(), material=mat)
        >> join
    )
    (
        atoms
        >> mg.SetColor(color=mg.ColorCommon())
        >> mg.StyleSticks(
            selection=sel_prox,
            scale=0.6,
            material=mat
        )
        >> join
    )

display(cv.snapshot())

mol.tree
```


## When is code evaluated

The `nodebpy` code is evaluated once, but the tree that is created will be re-evaluated every time a value or the Blender scene's frame changes.
We can set up a node tree that will animate as the frames change. The `AnimateValue` node uses the scene's current frame to interpolate between a starting and ending value (by default, `0` to `1`).

The node tree creation code below is evaluated once, but the selection changes on each frame  as the frame changes during animation playback, the resulting geometry that is created changes throughout the animation.


```{python}
cv.scene_reset()
animation_length = 100
cv.resolution = (720, 480)
cv.samples = 32
cv.frame_range = (1, animation_length)

mol = mn.Molecule.fetch("6n2y")
mat = mn.material.Flat(threshold=0.2).material

with mol.tree.reset() as (atoms, join):
    fac = mg.ChainParameter().o.factor
    frame = g.SceneTime().o.frame

    # the `.frame` value changes to reflect current scene.frame_current
    # we map that value to a range of 0 to 1 over the animation length, 
    # and use that to select fraction of the chain that is selected and drawn
    sel = fac < g.MapRange.float(frame, 1, animation_length, 0, 1)

    (
        atoms
        >> mg.GeoemtryToPlanar()
        >> mg.SetColor(color=mg.ColorRainbow())
        >> mg.StyleCartoon(selection=sel, loop_radius=0.7, material=mat)
        >> join
    )

cv.frame = animation_length
cv.look_at(mol, "top")

cv.animation()
```


```{python}
mol.tree
```