# Attributes

Below are the attributes which are potentially created when a structure is imported.
Explanations of type and domain conversions can be found in the Blender documentation [here](https://docs.blender.org/manual/en/latest/modeling/geometry_nodes/attributes_reference.html)

## World Scale

In Molecular Nodes, the world scale determines how real-world measurements are translated into the 3D environment of Blender which uses metres.
Currently, 1 nanometre (nm) is equivalent to 1 metre (m).
Scaling structural coordinates (which are in Å) by `0.1::Float` correctly converts them and `0.1::Float` is referred to as the `world_scale::Float`.

This changed with Molecular Nodes `v520`: previously the world scale was `0.01::Float`, so 1 Å equalled 1 cm.

When an attribute is going to be read from the geometry, it is colored red like so: `Index::Input`, `chain_id`, while when a specific data type is referenced it will be colored according to the data type like so: `Int::Int`, `Float::Float`, `Vector::Vector`, etc.

## Data Types

### Attribute Types

Attributes are always associated with `Geometry::Geometry`.
They will be stored on one of the [domains](#domains) of the geometry.
The type of the attribute is determined by the type of the data it contains.
The following types are supported by Geometry Nodes.

+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| Type                 | Description                                                                                                                                    |
+======================+================================================================================================================================================+
| `Int::Int`           | 32-bit integers                                                                                                                                |
+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| `Float::Float`       | 32-bit floating point numbers                                                                                                                  |
+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| `Bool::Bool`         | A simple `True::Bool` or `False::Bool` value                                                                                                   |
+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| `Vector::Vector`     | A vector of `(x, y, z)::Float` values. Can also be 2D, 3D or 4D although support outside of 3D vectors is limited.                             |
+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| `Matrix::Matrix`     | 4x4 floating point matrices, also references as `Transform::Matrix` inside of Geometry Nodes                                                   |
+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| `Color::Color`       | Linear RGBA colors, stored as `(0..1, 0..1, 0..1, 0..1)::Float` values                                                                         |
+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| `Rotation::Rotation` | A `(w, x, y, z)::Float` rotation that internally is represented as a quaternion, but can implicitly be converted to an `Euler::Vector` vector. |
+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------+

### Other Data Types

Additional data types which are not supported as Attributes but can be used in the node tree are:

+--------------------------+------------------------------------------------------------------------------------------------------+
| Type                     | Description                                                                                          |
+==========================+======================================================================================================+
| `String::String`         | String support in Geometry Nodes is limited at the moment and you cannot store strings as attributes |
+--------------------------+------------------------------------------------------------------------------------------------------+
| `Object::Object`         | Access to objects in the 3D scene and their associated data                                          |
+--------------------------+------------------------------------------------------------------------------------------------------+
| `Collection::Collection` | Access a collection of objects from the scene. Objects are returned as instances                     |
+--------------------------+------------------------------------------------------------------------------------------------------+
| `Material::Material`     | Material to be applied to the created geometry                                                       |
+--------------------------+------------------------------------------------------------------------------------------------------+
| `Menu::Menu`             | A menu for selecting a value from a list of options                                                  |
+--------------------------+------------------------------------------------------------------------------------------------------+
| `Image::Image`           | A reference to an image data-block, for sampling or texturing                                        |
+--------------------------+------------------------------------------------------------------------------------------------------+
| `Shader::Shader`         | The output of shader nodes, used when building materials rather than geometry                        |
+--------------------------+------------------------------------------------------------------------------------------------------+
| `Bundle::Bundle`         | New in Blender 5.0: multiple sockets packed together and passed along a single link                  |
+--------------------------+------------------------------------------------------------------------------------------------------+
| `Closure::Closure`       | New in Blender 5.0: a piece of node tree logic passed around as a value, to be evaluated elsewhere   |
+--------------------------+------------------------------------------------------------------------------------------------------+

## Attributes

All of the molecular attributes which are defined as strings such as `chain_id`, `res_name`, etc. are stored as integers in the geometry because Geometry Nodes does not support string attributes.

How the integer is assigned depends on the attribute. For the dynamic ones the strings are stored as metadata on the object, so an integer can be mapped back to its string (see [Reading Attributes from Python](#reading-attributes-from-python)):

| Attribute    | Integer assigned from                                          | Strings stored in            |
|--------------|----------------------------------------------------------------|------------------------------|
| `chain_id`   | Position in the alphabetically sorted list of unique chain IDs | `mol.props.chain_ids`        |
| `entity_id`  | Position in the `entity` category of the file, in file order   | `mol.props.entity_ids`       |
| `segid`      | Index of the segment, in topology order                        | `mol.props.segments`         |
| `atom_types` | Position in the sorted list of unique atom types               | `mol.props.atom_type_unique` |
| `res_name`   | Fixed [lookup table](data_table.qmd#residue-names)             |                              |
| `atom_name`  | Fixed [lookup table](data_table.qmd#atom-names)                |                              |

### Point Attributes

+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Attribute                | Type                   | Description                                                                                                                                                                          |
+:=========================+:=======================+:=====================================================================================================================================================================================+
| `Position`               | `Vector::Vector`       | Coordinates in 3D space of the points, read from the molecular data file. They are scaled by the world scale `0.1::Float` on import so that 1 nm == 1 m.                             |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `b_factor`               | `Float::Float`         | The temperature factor for the atom on import. If importing an AlphaFold structure this corresponds to the `pLDDT::Float` value.                                                     |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `occupancy`              | `Float::Float`         | The crystallographic occupancy of the atom, or `0.0::Float` if the file has none.                                                                                                    |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `charge`                 | `Float::Float`         | The charge of the atom, only present when the file or topology provides charges: partial charges from simulation topologies, formal charges from structure files.                    |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `vdw_radii`              | `Float::Float`         | The radii of the atom, stored in world space (\~`0.15::Float`). Values sourced from [Wikipedia](https://en.wikipedia.org/wiki/Atomic_radii_of_the_elements_(data_page)).             |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `sec_struct`             | `Int::Int`             | Defines secondary structure for the residue the atom is part of. `0::Int` for not a protein. `1::Int` for helices, `2::Int` for sheets, `3::Int` for coils / unstructured.           |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `mass`                   | `Float::Float`         | Mass of the element                                                                                                                                                                  |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `chain_id`               | `Int::Int`             | Position of the chain ID in the sorted list `mol.props.chain_ids`. For `.cif` and `.bcif` files this is the author chain ID (`auth_asym_id`), as in `.pdb` files.                    |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `segid`                  | `Int::Int`             | The index of the segment the atom belongs to, when the topology defines segments. The segment names are stored as metadata on the object.                                            |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `entity_id`              | `Int::Int`             | Multiple chains can be the same `entity`, if they are copies of the same protein in the structure. Only `.cif` and `.bcif` files define entities. Numbered in the file's order.      |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `res_name`               | `Int::Int`             | Residues are mapped to integer values based on the [lookup table](data_table.qmd#residue-names).                                                                                     |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `res_id`                 | `Int::Int`             | The residue number, which starts at `1::Int` for the first residue in each chain. If a structure is truncated it might not start at 1.                                               |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `ures_id`                | `Int::Int`             | The `ures_id` starts at `0::Int` and increases by 1 for each residue across the whole structure, compared to the `res_id` which starts at `1::Int` and restarts at 1 for each chain. |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `atomic_number`          | `Int::Int`             | Stores the atomic number of the atom for it's position on the periodic table, instead of the element's name.                                                                         |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `atom_name`              | `Int::Int`             | Atom names are mapped to integer values based on the [lookup table](data_table.qmd#atom-names).                                                                                      |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `atom_types`             | `Int::Int`             | The force-field atom types from simulation topologies, sorted uniquely and assigned integers on import. The type names are stored as metadata on the object.                         |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `Color`                  | `Color::Color`         | Color of the atom, assigned on import but often changed in node trees.                                                                                                               |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `atom_id`                | `Int::Int`             | Unique ascending value for each atom in the file, starting at `1::Int`                                                                                                               |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `is_alpha_carbon`        | `Bool::Bool`           | Whether the atom is an alpha carbon (atom name `CA`, or `BB` for coarse-grained structures) of an amino acid residue. Ions and ligands are excluded.                                 |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `is_side_chain`          | `Bool::Bool`           | Whether the atom is part of a side chain: an atom of an amino acid or nucleotide residue that is not part of the backbone. The alpha carbon also counts as side chain.               |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `is_backbone`            | `Bool::Bool`           | Whether the atom is part of the peptide or nucleic backbone, based on its atom name, in amino acid and nucleotide residues. Ions and ligands are excluded.                           |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `is_solvent`             | `Bool::Bool`           | Whether the atom is part of a solvent molecule (such as water), based on its residue and atom names.                                                                                 |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `is_nucleic`             | `Bool::Bool`           | Whether the atom is part of a residue MDAnalysis recognises as a nucleic acid.                                                                                                       |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `is_peptide`             | `Bool::Bool`           | Whether the atom is part of an amino acid residue, including modified residues (such as `HIC`) and coarse-grained (Martini) `BB` or `SC*` beads.                                     |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `is_lipid`               | `Bool::Bool`           | Whether the atom is part of a lipid, based on its residue name.                                                                                                                      |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `is_hetero`              | `Bool::Bool`           | Whether the atom is flagged as a hetero atom in the structure file.                                                                                                                  |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `is_carb`                | `Bool::Bool`           | Whether the atom is part of a carbohydrate, based on its residue name.                                                                                                               |
+--------------------------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### Edge Attributes

Bonds between atoms are represented as edges in the geometry, and only the bond type is stored on the edge domain.

| Attribute   | Type       | Description                         |
|-------------|------------|-------------------------------------|
| `bond_type` | `Int::Int` | The type of bond between the atoms. |

Bond types are currently the values used by [`biotite`](https://www.biotite-python.org/latest/apidoc/biotite.structure.BondType.html)

+---------------------------+---------------+-----------------------------------------+
| Bond Type                 | Integer Value | Description                             |
+===========================+:=============:+=========================================+
| `ANY::String`             | `0::Int`      | Used if the actual type is unknown      |
+---------------------------+---------------+-----------------------------------------+
| `SINGLE::String`          | `1::Int`      | Single bond                             |
+---------------------------+---------------+-----------------------------------------+
| `DOUBLE::String`          | `2::Int`      | Double bond                             |
+---------------------------+---------------+-----------------------------------------+
| `TRIPLE::String`          | `3::Int`      | Triple bond                             |
+---------------------------+---------------+-----------------------------------------+
| `QUADRUPLE::String`       | `4::Int`      | A quadruple bond                        |
+---------------------------+---------------+-----------------------------------------+
| `AROMATIC_SINGLE::String` | `5::Int`      | Aromatic bond with a single formal bond |
+---------------------------+---------------+-----------------------------------------+
| `AROMATIC_DOUBLE::String` | `6::Int`      | Aromatic bond with a double formal bond |
+---------------------------+---------------+-----------------------------------------+
| `AROMATIC_TRIPLE::String` | `7::Int`      | Aromatic bond with a triple formal bond |
+---------------------------+---------------+-----------------------------------------+

### Attributes by Format

Which attributes are created depends on what the file provides.
These attributes are created for every format: `position`, `atomic_number`, `atom_name`, `atom_types`, `res_name`, `res_id`, `segid`, `mass`, `vdw_radii`, `b_factor`, `occupancy`, `Color` and the `is_*` flags except `is_hetero` and `is_carb`.
The others vary:

| Attribute    | `.pdb`         | `.cif` / `.bcif` | `.sdf` / `.mol` | MD topology                 |
|--------------|:--------------:|:----------------:|:---------------:|:---------------------------:|
| `chain_id`   | ✓              | ✓                | ✓               |                             |
| `entity_id`  |                | ✓                |                 |                             |
| `ures_id`    | ✓              | ✓                | ✓               |                             |
| `atom_id`    | ✓              | ✓                |                 | ✓                           |
| `sec_struct` | ✓              | ✓                |                 | ✓                           |
| `is_hetero`  | ✓              | ✓                | ✓               |                             |
| `is_carb`    | ✓              | ✓                | ✓               |                             |
| `bond_type`  | ✓              | ✓                | ✓               |                             |
| `charge`     | if in the file | if in the file   | if in the file  | if the topology has charges |

Simulation topologies differ in what they contain, so the MD column is for typical topologies such as `.psf` and `.gro`.
`mol.list_attributes()` lists the attributes on a molecule, and `mol.named_attribute()` raises an error for one that was not created.
In the node tree there is no error: reading a missing attribute gives `0::Int` (or `False::Bool`) for every atom, so selecting by `entity_id` on a `.pdb` file treats every atom as entity `0::Int`.

### Reading Attributes from Python

`mol.named_attribute()` returns the attribute stored on the object as a `numpy` array, one value per atom.
The integer attributes in the table above can be mapped back to their strings with the stored metadata:

```python
import numpy as np
import molecularnodes as mn

mol = mn.Molecule.fetch("1CD3", format="cif")

chain_id = mol.named_attribute("chain_id")
chain_names = np.array(mol.props.chain_ids)[chain_id]  # e.g. "1", "2", "B"

is_alpha_carbon = mol.named_attribute("is_alpha_carbon")
print(np.unique(chain_names[is_alpha_carbon], return_counts=True))
```

`position` is in Blender units, the coordinates in Å scaled by the [world scale](#world-scale), for the current frame and before any node tree changes.
`mol.universe.atoms.positions` has the same coordinates in Å.

`mol.named_attribute(name, evaluate=True)` instead reads the geometry after the node tree is evaluated, which is not one point per atom once a style is applied.
A cartoon is a mesh with many more vertices than there are atoms, and spheres are instances by default so the evaluated mesh is empty.
To get atom positions, read the stored `position` or the universe instead of the evaluated geometry.

## Domains {#domains}

+----------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Domain               | Description                                                                                                                        |
+======================+====================================================================================================================================+
| `Point::Geometry`    | Individual points of geometry. These can be the vertices in a mesh, the points in a point cloud, or the control points of a curve. |
+----------------------+------------------------------------------------------------------------------------------------------------------------------------+
| `Edge::Geometry`     | The edges of a mesh, defined as the indices between two points.                                                                    |
+----------------------+------------------------------------------------------------------------------------------------------------------------------------+
| `Face::Geometry`     | A face of a mesh, defined as a collection of edges.                                                                                |
+----------------------+------------------------------------------------------------------------------------------------------------------------------------+
| `Corner::Geometry`   | Corners of a face, where two edges meet.                                                                                           |
+----------------------+------------------------------------------------------------------------------------------------------------------------------------+
| `Curve::Geometry`    | A curve object, which contains multiple control points, but can itself store attributes.                                           |
+----------------------+------------------------------------------------------------------------------------------------------------------------------------+
| `Instance::Geometry` | Instances are references to other geometry. Instancing is useful for making lots of copies of some geometry for performance.       |
+----------------------+------------------------------------------------------------------------------------------------------------------------------------+
| `Layer::Geometry`    | Layers are for Grease Pencil, and contain a collection of curves.                                                                  |
+----------------------+------------------------------------------------------------------------------------------------------------------------------------+
