
-- Colors inline code as node-socket chips: `Name::Type` renders as `Name`
-- with the class `custom-<type>`, styled by the $custom-classes map in
-- style.scss — every keyword here needs a matching entry there. The socket
-- tables generated by docs/generate.py and docs/_renderer.py tag their type
-- cells this way.
local keywords = {
  "Float", "Int", "Vector", "Geometry", "Bool", "Matrix", "Rotation",
  "Material", "Color", "Collection", "String", "Name", "Object", "Input",
  "Menu", "Shader", "Image", "Bundle", "Closure",
}
local attributes = {"sec_struct", "res_id", "chain_id", "entity_id", "res_name", "atom_name", "atom_id", "ures_id", "occupancy", "bfactor", "atomic_number", "charge", "vdw_radii", "mass", "lipophobicity", "segid", "atom_types", "is_backbone", "is_side_chain", "is_alpha_carbon", "Position", "Index", "Normal", "ID", "b_factor", "is_solvent", "is_nucleic", "is_peptide", "is_hetero", "is_carb", "is_lipid", "bond_type", "Color"}

local special_mappings = {
  ["True"] = "True::Bool",
  ["False"] = "False::Bool",
  -- ["None"] = "None::Object",
}

-- `Name::Node` links to the node's entry in the node documentation, using the
-- name -> href map that docs/generate.py writes to _node_links.lua
local script_dir = pandoc.path.directory(PANDOC_SCRIPT_FILE)
local found, node_links = pcall(dofile, pandoc.path.join({script_dir, "_node_links.lua"}))
if not found then
  node_links = {}
end

function Code(el)
  if special_mappings[el.text] then
    el.text = special_mappings[el.text]
  end
  if el.text:match("^'.*'$") then
    el.text = el.text ..  "::String"
  end
  local node_name = el.text:match("^(.+)::Node$")
  if node_name then
    el.text = node_name
    table.insert(el.classes, "custom-node")
    local href = node_links[node_name]
    if href == nil then
      quarto.log.warning("`" .. node_name .. "::Node` matches no documented node")
      return el
    end
    return pandoc.Link(el, href)
  end
  for _, keyword in ipairs(keywords) do
    -- anchored so e.g. `x::Int` never matches inside `x::Integer`
    local name = el.text:match("^(.+)::" .. keyword .. "$")
    if name then
      table.insert(el.classes, "custom-" .. keyword:lower())
      el.text = name
      return el
    end
  end
  for _, attribute in ipairs(attributes) do
    if el.text == attribute then
      table.insert(el.classes, "custom-attribute")
      return el
    end
  end
end
