elements = {
        "H"  : {"atomic_number" :  1, "name" : "Hydrogen"    },
        "He" : {"atomic_number" :  2, "name" : "Helium"      },
        "Li" : {"atomic_number" :  3, "name" : "Lithium"     },
        "Be" : {"atomic_number" :  4, "name" : "Beryllium"   },
        "B"  : {"atomic_number" :  5, "name" : "Boron"       },
        "C"  : {"atomic_number" :  6, "name" : "Carbon"      },
        "N"  : {"atomic_number" :  7, "name" : "Nitrogen"    },
        "O"  : {"atomic_number" :  8, "name" : "Oxygen"      },
        "F"  : {"atomic_number" :  9, "name" : "Fluorine"    },
        "Ne" : {"atomic_number" : 10, "name" : "Neon"        },
        "Na" : {"atomic_number" : 11, "name" : "Sodium"      },
        "Mg" : {"atomic_number" : 12, "name" : "Magnesium"   },
        "Al" : {"atomic_number" : 13, "name" : "Aluminium"   },
        "Si" : {"atomic_number" : 14, "name" : "Silicon"     },
        "P"  : {"atomic_number" : 15, "name" : "Phosphorus"  },
        "S"  : {"atomic_number" : 16, "name" : "Sulfur"      },
        "Cl" : {"atomic_number" : 17, "name" : "Chlorine"    },
        "Ar" : {"atomic_number" : 18, "name" : "Argon"       },
        "K"  : {"atomic_number" : 19, "name" : "Potassium"   },
        "Ca" : {"atomic_number" : 20, "name" : "Calcium"     },
        "Sc" : {"atomic_number" : 21, "name" : "Scandium"    },
        "Ti" : {"atomic_number" : 22, "name" : "Titanium"    },
        "V"  : {"atomic_number" : 23, "name" : "Vanadium"    },
        "Cr" : {"atomic_number" : 24, "name" : "Chromium"    },
        "Mn" : {"atomic_number" : 25, "name" : "Manganese"   },
        "Fe" : {"atomic_number" : 26, "name" : "Iron"        },
        "Co" : {"atomic_number" : 27, "name" : "Cobalt"      },
        "Ni" : {"atomic_number" : 28, "name" : "Nickel"      },
        "Cu" : {"atomic_number" : 29, "name" : "Copper"      },
        "Zn" : {"atomic_number" : 30, "name" : "Zinc"        },
        "Ga" : {"atomic_number" : 31, "name" : "Gallium"     },
        "Ge" : {"atomic_number" : 32, "name" : "Germanium"   },
        "As" : {"atomic_number" : 33, "name" : "Arsenic"     },
        "Se" : {"atomic_number" : 34, "name" : "Selenium"    },
        "Br" : {"atomic_number" : 35, "name" : "Bromine"     },
        "Kr" : {"atomic_number" : 36, "name" : "Krypton"     },
        "Rb" : {"atomic_number" : 37, "name" : "Rubidium"    },
        "Sr" : {"atomic_number" : 38, "name" : "Strontium"   },
        "Y"  : {"atomic_number" : 39, "name" : "Yttrium"     },
        "Zr" : {"atomic_number" : 40, "name" : "Zirconium"   },
        "Nb" : {"atomic_number" : 41, "name" : "Niobium"     },
        "Mo" : {"atomic_number" : 42, "name" : "Molybdenum"  },
        "Tc" : {"atomic_number" : 43, "name" : "Technetium"  },
        "Ru" : {"atomic_number" : 44, "name" : "Ruthenium"   },
        "Rh" : {"atomic_number" : 45, "name" : "Rhodium"     },
        "Pd" : {"atomic_number" : 46, "name" : "Palladium"   },
        "Ag" : {"atomic_number" : 47, "name" : "Silver"      },
        "Cd" : {"atomic_number" : 48, "name" : "Cadmium"     },
        "In" : {"atomic_number" : 49, "name" : "Indium"      },
        "Sn" : {"atomic_number" : 50, "name" : "Tin"         },
        "Sb" : {"atomic_number" : 51, "name" : "Antimony"    },
        "Te" : {"atomic_number" : 52, "name" : "Tellurium"   },
        "I"  : {"atomic_number" : 53, "name" : "Iodine"      },
        "Xe" : {"atomic_number" : 54, "name" : "Xenon"       },
        "Cs" : {"atomic_number" : 55, "name" : "Caesium"     },
        "Ba" : {"atomic_number" : 56, "name" : "Barium"      },
        "La" : {"atomic_number" : 57, "name" : "Lanthanum"   },
        "Ce" : {"atomic_number" : 58, "name" : "Cerium"      },
        "Pr" : {"atomic_number" : 59, "name" : "Praseodymium"},
        "Nd" : {"atomic_number" : 60, "name" : "Neodymium"   },
        "Pm" : {"atomic_number" : 61, "name" : "Promethium"  },
        "Sm" : {"atomic_number" : 62, "name" : "Samarium"    },
        "Eu" : {"atomic_number" : 63, "name" : "Europium"    },
        "Gd" : {"atomic_number" : 64, "name" : "Gadolinium"  },
        "Tb" : {"atomic_number" : 65, "name" : "Terbium"     },
        "Dy" : {"atomic_number" : 66, "name" : "Dysprosium"  },
        "Ho" : {"atomic_number" : 67, "name" : "Holmium"     },
        "Er" : {"atomic_number" : 68, "name" : "Erbium"      },
        "Tm" : {"atomic_number" : 69, "name" : "Thulium"     },
        "Yb" : {"atomic_number" : 70, "name" : "Ytterbium"   },
        "Lu" : {"atomic_number" : 71, "name" : "Lutetium"    },
        "Hf" : {"atomic_number" : 72, "name" : "Hafnium"     },
        "Ta" : {"atomic_number" : 73, "name" : "Tantalum"    },
        "W"  : {"atomic_number" : 74, "name" : "Tungsten"    },
        "Re" : {"atomic_number" : 75, "name" : "Rhenium"     },
        "Os" : {"atomic_number" : 76, "name" : "Osmium"      },
        "Ir" : {"atomic_number" : 77, "name" : "Iridium"     },
        "Pt" : {"atomic_number" : 78, "name" : "Platinum"    },
        "Au" : {"atomic_number" : 79, "name" : "Gold"        },
        "Hg" : {"atomic_number" : 80, "name" : "Mercury"     },
        "Tl" : {"atomic_number" : 81, "name" : "Thallium"    },
        "Pb" : {"atomic_number" : 82, "name" : "Lead"        },
        "Bi" : {"atomic_number" : 83, "name" : "Bismuth"     },
        "Po" : {"atomic_number" : 84, "name" : "Polonium"    },
        "At" : {"atomic_number" : 85, "name" : "Astatine"    },
        "Rn" : {"atomic_number" : 86, "name" : "Radon"       },
        "Fr" : {"atomic_number" : 87, "name" : "Francium"    },
        "Ra" : {"atomic_number" : 88, "name" : "Radium"      },
        "Ac" : {"atomic_number" : 89, "name" : "Actinium"    },
        "Th" : {"atomic_number" : 90, "name" : "Thorium"     },
        "Pa" : {"atomic_number" : 91, "name" : "Protactinium"},
        "U"  : {"atomic_number" : 92, "name" : "Uranium"     },
        "Np" : {"atomic_number" : 93, "name" : "Neptunium"   },
        "Pu" : {"atomic_number" : 94, "name" : "Plutonium"   },
        "Am" : {"atomic_number" : 95, "name" : "Americium"   },
        "Cm" : {"atomic_number" : 96, "name" : "Curium"      },
        "Bk" : {"atomic_number" : 97, "name" : "Berkelium"   },
        "Cf" : {"atomic_number" : 98, "name" : "Californium" },
        "Es" : {"atomic_number" : 99, "name" : "Einsteinium" },
        "Fm" : {"atomic_number" : 100, "name" : "Fermium"    },
        "Md" : {"atomic_number" : 101, "name" : "Mendelevium"},
        "No" : {"atomic_number" : 102, "name" : "Nobelium"   },
        "Lr" : {"atomic_number" : 103, "name" : "Lawrencium" }
    }

amino_acids = {
    # 20 naturally occurring amino acids
    "ALA": {"aa_number": 1, "aa_type": "apolar", "aa_type_no": 1},
    "ARG": {"aa_number": 2, "aa_type": "basic", "aa_type_no": 1},
    "ASN": {"aa_number": 3, "aa_type": "polar", "aa_type_no": 1},
    "ASP": {"aa_number": 4, "aa_type": "acid", "aa_type_no": 1},
    "CYS": {"aa_number": 5, "aa_type": "polar", "aa_type_no": 1}, #can act as acid, but mostly polar?
    "GLU": {"aa_number": 6, "aa_type": "acid", "aa_type_no": 1},
    "GLN": {"aa_number": 7, "aa_type": "polar", "aa_type_no": 1},
    "GLY": {"aa_number": 8, "aa_type": "apolar", "aa_type_no": 1},
    "HIS": {"aa_number": 9, "aa_type": "polar", "aa_type_no": 1}, #ambiguous
    "ILE": {"aa_number": 10, "aa_type": "apolar", "aa_type_no": 1},
    "LEU": {"aa_number": 11, "aa_type": "apolar", "aa_type_no": 1},
    "LYS": {"aa_number": 12, "aa_type": "basic", "aa_type_no": 1},
    "MET": {"aa_number": 13, "aa_type": "apolar", "aa_type_no": 1},
    "PHE": {"aa_number": 14, "aa_type": "aromatic", "aa_type_no": 1},
    "PRO": {"aa_number": 15, "aa_type": "apolar", "aa_type_no": 1},
    "SER": {"aa_number": 16, "aa_type": "polar", "aa_type_no": 1},
    "THR": {"aa_number": 17, "aa_type": "polar", "aa_type_no": 1},
    "TRP": {"aa_number": 18, "aa_type": "aromatic", "aa_type_no": 1},
    "TYR": {"aa_number": 19, "aa_type": "aromatic", "aa_type_no": 1},
    "VAL": {"aa_number": 20, "aa_type": "apolar", "aa_type_no": 1},
    # add conventional AMBER FF residue names with different protonations
    "ASH": {"aa_number": 4, "aa_type": "acid", "aa_type_no": 1},
    "CYM": {"aa_number": 5, "aa_type": "polar", "aa_type_no": 1},
    "CYX": {"aa_number": 5, "aa_type": "polar", "aa_type_no": 1},
    "GLH": {"aa_number": 6, "aa_type": "acid", "aa_type_no": 1},
    "HID": {"aa_number": 9, "aa_type": "polar", "aa_type_no": 1},
    "HIE": {"aa_number": 9, "aa_type": "polar", "aa_type_no": 1},
    "HIP": {"aa_number": 9, "aa_type": "polar", "aa_type_no": 1},
    "HYP": {"aa_number": 9, "aa_type": "polar", "aa_type_no": 1},
    "LYN": {"aa_number": 12, "aa_type": "basic", "aa_type_no": 1},
    # unknown? Came up in one of the structures, haven't looked into it yet
    # TODO look into it!
    "UNK": {"aa_number": 21, "aa_type": "unkown", "aa_type_no": 1},
    # nucleic acids
    # DNA
    "DA": {"aa_number": 31, "aa_type": "unkown", "aa_type_no": 1},
    "DC": {"aa_number": 32, "aa_type": "unkown", "aa_type_no": 1},
    "DG": {"aa_number": 33, "aa_type": "unkown", "aa_type_no": 1},
    "DT": {"aa_number": 34, "aa_type": "unkown", "aa_type_no": 1},
    # RNA
    "A": {"aa_number": 41, "aa_type": "unkown", "aa_type_no": 1},
    "C": {"aa_number": 42, "aa_type": "unkown", "aa_type_no": 1},
    "G": {"aa_number": 43, "aa_type": "unkown", "aa_type_no": 1},
    "U": {"aa_number": 44, "aa_type": "unkown", "aa_type_no": 1}
}