# nodes { #nodes }

``

## Attributes

| Name | Description |
| --- | --- |
| [socket_types](#nodes.socket_types) |  |

## Functions

| Name | Description |
| --- | --- |
| [add_custom_node_group](#nodes.add_custom_node_group) |  |
| [add_custom_node_group_to_node](#nodes.add_custom_node_group_to_node) |  |
| [chain_color](#nodes.chain_color) | Given the input list of chain names, will create a node group which uses |
| [chain_selection](#nodes.chain_selection) | Given a an input_list, will create a node which takes an Integer input,  |
| [create_custom_surface](#nodes.create_custom_surface) |  |
| [create_starting_node_tree](#nodes.create_starting_node_tree) |  |
| [create_starting_nodes_density](#nodes.create_starting_nodes_density) |  |
| [create_starting_nodes_starfile](#nodes.create_starting_nodes_starfile) |  |
| [gn_new_group_empty](#nodes.gn_new_group_empty) |  |
| [mol_append_node](#nodes.mol_append_node) |  |
| [mol_base_material](#nodes.mol_base_material) | Append MOL_atomic_material to the .blend file it it doesn't already exist, and return that material. |
| [resid_multiple_selection](#nodes.resid_multiple_selection) | Returns a node group that takes an integer input and creates a boolean  |
| [rotation_matrix](#nodes.rotation_matrix) | Add a Rotation & Translation node from a 3x4 matrix. |

## add_custom_node_group { #nodes.add_custom_node_group }

`add_custom_node_group(parent_group, node_name, location=\[0, 0\], width=200)`

## add_custom_node_group_to_node { #nodes.add_custom_node_group_to_node }

`add_custom_node_group_to_node(parent_group, node_name, location=\[0, 0\], width=200)`

## chain_color { #nodes.chain_color }

`chain_color(node_name, input_list, label_prefix='Chain ')`

Given the input list of chain names, will create a node group which uses
the chain_id named attribute to manually set the colours for each of the chains.

## chain_selection { #nodes.chain_selection }

`chain_selection(node_name, input_list, attribute, starting_value=0, label_prefix='')`

Given a an input_list, will create a node which takes an Integer input, 
and has a boolean tick box for each item in the input list. The outputs will
be the resulting selection and the inversion of the selection.
Can contain a prefix for the resulting labels. Mostly used for constructing 
chain selections when required for specific proteins.

## create_custom_surface { #nodes.create_custom_surface }

`create_custom_surface(name, n_chains)`

## create_starting_node_tree { #nodes.create_starting_node_tree }

`create_starting_node_tree(obj, coll_frames, starting_style='atoms')`

## create_starting_nodes_density { #nodes.create_starting_nodes_density }

`create_starting_nodes_density(obj)`

## create_starting_nodes_starfile { #nodes.create_starting_nodes_starfile }

`create_starting_nodes_starfile(obj)`

## gn_new_group_empty { #nodes.gn_new_group_empty }

`gn_new_group_empty(name='Geometry Nodes')`

## mol_append_node { #nodes.mol_append_node }

`mol_append_node(node_name)`

## mol_base_material { #nodes.mol_base_material }

`mol_base_material()`

Append MOL_atomic_material to the .blend file it it doesn't already exist, and return that material.

## resid_multiple_selection { #nodes.resid_multiple_selection }

`resid_multiple_selection(node_name, input_resid_string)`

Returns a node group that takes an integer input and creates a boolean 
tick box for each item in the input list. Outputs are the selected 
residues and the inverse selection. Used for constructing chain 
selections in specific proteins.

## rotation_matrix { #nodes.rotation_matrix }

`rotation_matrix(node_group, mat, location=\[0, 0\], world_scale=0.01)`

Add a Rotation & Translation node from a 3x4 matrix.

Args:
    node_group (_type_): Parent node group to add this new node to.
    mat (_type_): 3x4 rotation & translation matrix
    location (list, optional): Position to add the node in the node tree. Defaults to [0,0].
    world_scale(float, optional): Scaling factor for the world. Defaults to 0.01.
Returns:
    _type_: Newly created node tree.