name: benchmarks

on:
  push:
    branches: "*"
  pull_request:
    branches: main

jobs:
  benchmark_base_branch:
    name: Benchmarking
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Install Packages
        run: |
          uv sync --all-extras
          uv pip install -e .
      - uses: bencherdev/bencher@main
      - name: Track base branch benchmarks with Bencher
        run: |
          bencher run \
          --project molecularnodes \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch ${{ github.base_ref }} \
          --testbed ${{ runner.os }}-${{ runner.name }} \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.99 \
          --thresholds-reset \
          --err \
          --adapter python_pytest \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --file results.json \
          "pytest --benchmark-json results.json benchmarks"