name: Code Lint with Ruff

on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main", "4.4"]


jobs:
    lint:
      name: Check code style
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install ruff
        run: pip install ruff
      - name: Check code formatting
        run: ruff format --diff
      - name: Lint code base
        run: ruff check
