name: GPU Render Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

# Cancel in-progress runs when a new workflow with the same group is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  render-tests:
    name: Image Rendering Tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install molecularnodes
        run: |
          uv sync --all-extras

      - name: Run Image Snapshot Tests
        timeout-minutes: 10
        run: |
          uv run pytest -v -m image_snapshot --image-snapshot-save-diff --junitxml=test-results.xml

      - name: Upload Image Diff Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: image-diffs-gpu
          retention-days: 7
          path: tests/__image_snapshots__/__diff_output__/

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-gpu
          retention-days: 7
          path: test-results.xml
